// Code generated by MockGen. DO NOT EDIT.
// Source: data-service/service (interfaces: IDorisService)

// Package mocks is a generated GoMock package.
package mocks

import (
	datasource "data-service/generated/datasource"
	sql "database/sql"
	reflect "reflect"

	arrow "github.com/apache/arrow/go/v15/arrow"
	gomock "github.com/golang/mock/gomock"
)

// MockIDorisService is a mock of IDorisService interface.
type MockIDorisService struct {
	ctrl     *gomock.Controller
	recorder *MockIDorisServiceMockRecorder
}

// MockIDorisServiceMockRecorder is the mock recorder for MockIDorisService.
type MockIDorisServiceMockRecorder struct {
	mock *MockIDorisService
}

// NewMockIDorisService creates a new mock instance.
func NewMockIDorisService(ctrl *gomock.Controller) *MockIDorisService {
	mock := &MockIDorisService{ctrl: ctrl}
	mock.recorder = &MockIDorisServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDorisService) EXPECT() *MockIDorisServiceMockRecorder {
	return m.recorder
}

// CleanDorisTableWithPrefix mocks base method.
func (m *MockIDorisService) CleanDorisTableWithPrefix(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanDorisTableWithPrefix", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanDorisTableWithPrefix indicates an expected call of CleanDorisTableWithPrefix.
func (mr *MockIDorisServiceMockRecorder) CleanDorisTableWithPrefix(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanDorisTableWithPrefix", reflect.TypeOf((*MockIDorisService)(nil).CleanDorisTableWithPrefix), arg0)
}

// Close mocks base method.
func (m *MockIDorisService) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIDorisServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIDorisService)(nil).Close))
}

// ConvertRequestToArrowSchema mocks base method.
func (m *MockIDorisService) ConvertRequestToArrowSchema(arg0 *datasource.ExportDorisDataToMiraDBRequest) (*arrow.Schema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertRequestToArrowSchema", arg0)
	ret0, _ := ret[0].(*arrow.Schema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertRequestToArrowSchema indicates an expected call of ConvertRequestToArrowSchema.
func (mr *MockIDorisServiceMockRecorder) ConvertRequestToArrowSchema(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertRequestToArrowSchema", reflect.TypeOf((*MockIDorisService)(nil).ConvertRequestToArrowSchema), arg0)
}

// CreateExternalAndInternalTableAndImportData mocks base method.
func (m *MockIDorisService) CreateExternalAndInternalTableAndImportData(arg0, arg1, arg2, arg3, arg4, arg5 string, arg6 ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3, arg4, arg5}
	for _, a := range arg6 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateExternalAndInternalTableAndImportData", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExternalAndInternalTableAndImportData indicates an expected call of CreateExternalAndInternalTableAndImportData.
func (mr *MockIDorisServiceMockRecorder) CreateExternalAndInternalTableAndImportData(arg0, arg1, arg2, arg3, arg4, arg5 interface{}, arg6 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3, arg4, arg5}, arg6...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExternalAndInternalTableAndImportData", reflect.TypeOf((*MockIDorisService)(nil).CreateExternalAndInternalTableAndImportData), varargs...)
}

// CreateExternalAndInternalTableAndImportDataBatched mocks base method.
func (m *MockIDorisService) CreateExternalAndInternalTableAndImportDataBatched(arg0, arg1, arg2, arg3, arg4, arg5, arg6 string, arg7 int, arg8 ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7}
	for _, a := range arg8 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateExternalAndInternalTableAndImportDataBatched", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExternalAndInternalTableAndImportDataBatched indicates an expected call of CreateExternalAndInternalTableAndImportDataBatched.
func (mr *MockIDorisServiceMockRecorder) CreateExternalAndInternalTableAndImportDataBatched(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 interface{}, arg8 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7}, arg8...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExternalAndInternalTableAndImportDataBatched", reflect.TypeOf((*MockIDorisService)(nil).CreateExternalAndInternalTableAndImportDataBatched), varargs...)
}

// CreateExternalTableFromAsset mocks base method.
func (m *MockIDorisService) CreateExternalTableFromAsset(arg0, arg1, arg2, arg3, arg4, arg5 string, arg6 ...string) ([]string, string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3, arg4, arg5}
	for _, a := range arg6 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateExternalTableFromAsset", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateExternalTableFromAsset indicates an expected call of CreateExternalTableFromAsset.
func (mr *MockIDorisServiceMockRecorder) CreateExternalTableFromAsset(arg0, arg1, arg2, arg3, arg4, arg5 interface{}, arg6 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3, arg4, arg5}, arg6...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExternalTableFromAsset", reflect.TypeOf((*MockIDorisService)(nil).CreateExternalTableFromAsset), varargs...)
}

// DropDatabase mocks base method.
func (m *MockIDorisService) DropDatabase(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropDatabase", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropDatabase indicates an expected call of DropDatabase.
func (mr *MockIDorisServiceMockRecorder) DropDatabase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropDatabase", reflect.TypeOf((*MockIDorisService)(nil).DropDatabase), arg0)
}

// DropTable mocks base method.
func (m *MockIDorisService) DropTable(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropTable", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropTable indicates an expected call of DropTable.
func (mr *MockIDorisServiceMockRecorder) DropTable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropTable", reflect.TypeOf((*MockIDorisService)(nil).DropTable), arg0, arg1)
}

// EnsureDorisDatabaseExists mocks base method.
func (m *MockIDorisService) EnsureDorisDatabaseExists(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDorisDatabaseExists", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureDorisDatabaseExists indicates an expected call of EnsureDorisDatabaseExists.
func (mr *MockIDorisServiceMockRecorder) EnsureDorisDatabaseExists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDorisDatabaseExists", reflect.TypeOf((*MockIDorisService)(nil).EnsureDorisDatabaseExists), arg0)
}

// ExecuteSQL mocks base method.
func (m *MockIDorisService) ExecuteSQL(arg0 string, arg1 ...interface{}) (*sql.Rows, func(), error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteSQL", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExecuteSQL indicates an expected call of ExecuteSQL.
func (mr *MockIDorisServiceMockRecorder) ExecuteSQL(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteSQL", reflect.TypeOf((*MockIDorisService)(nil).ExecuteSQL), varargs...)
}

// ExecuteUpdate mocks base method.
func (m *MockIDorisService) ExecuteUpdate(arg0 string, arg1 ...interface{}) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteUpdate", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteUpdate indicates an expected call of ExecuteUpdate.
func (mr *MockIDorisServiceMockRecorder) ExecuteUpdate(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteUpdate", reflect.TypeOf((*MockIDorisService)(nil).ExecuteUpdate), varargs...)
}

// ExportDorisDataToMiraDB mocks base method.
func (m *MockIDorisService) ExportDorisDataToMiraDB(arg0 *datasource.ExportDorisDataToMiraDBRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportDorisDataToMiraDB", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportDorisDataToMiraDB indicates an expected call of ExportDorisDataToMiraDB.
func (mr *MockIDorisServiceMockRecorder) ExportDorisDataToMiraDB(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportDorisDataToMiraDB", reflect.TypeOf((*MockIDorisService)(nil).ExportDorisDataToMiraDB), arg0)
}

// ExportParquetFileFromDoris mocks base method.
func (m *MockIDorisService) ExportParquetFileFromDoris(arg0 *datasource.ExportCsvFileFromDorisRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportParquetFileFromDoris", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportParquetFileFromDoris indicates an expected call of ExportParquetFileFromDoris.
func (mr *MockIDorisServiceMockRecorder) ExportParquetFileFromDoris(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportParquetFileFromDoris", reflect.TypeOf((*MockIDorisService)(nil).ExportParquetFileFromDoris), arg0)
}

// GetDBName mocks base method.
func (m *MockIDorisService) GetDBName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDBName indicates an expected call of GetDBName.
func (mr *MockIDorisServiceMockRecorder) GetDBName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBName", reflect.TypeOf((*MockIDorisService)(nil).GetDBName))
}

// GetDorisTableSchema mocks base method.
func (m *MockIDorisService) GetDorisTableSchema(arg0, arg1 string) ([]*datasource.ColumnItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDorisTableSchema", arg0, arg1)
	ret0, _ := ret[0].([]*datasource.ColumnItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDorisTableSchema indicates an expected call of GetDorisTableSchema.
func (mr *MockIDorisServiceMockRecorder) GetDorisTableSchema(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDorisTableSchema", reflect.TypeOf((*MockIDorisService)(nil).GetDorisTableSchema), arg0, arg1)
}

// ImportArrowFileToDoris mocks base method.
func (m *MockIDorisService) ImportArrowFileToDoris(arg0, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportArrowFileToDoris", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportArrowFileToDoris indicates an expected call of ImportArrowFileToDoris.
func (mr *MockIDorisServiceMockRecorder) ImportArrowFileToDoris(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportArrowFileToDoris", reflect.TypeOf((*MockIDorisService)(nil).ImportArrowFileToDoris), arg0, arg1, arg2, arg3)
}

// ImportCsvFileToDoris mocks base method.
func (m *MockIDorisService) ImportCsvFileToDoris(arg0 *datasource.ImportCsvFileToDorisRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportCsvFileToDoris", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportCsvFileToDoris indicates an expected call of ImportCsvFileToDoris.
func (mr *MockIDorisServiceMockRecorder) ImportCsvFileToDoris(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportCsvFileToDoris", reflect.TypeOf((*MockIDorisService)(nil).ImportCsvFileToDoris), arg0)
}

// ImportMiraDBDataToDoris mocks base method.
func (m *MockIDorisService) ImportMiraDBDataToDoris(arg0 *datasource.ImportMiraDBDataToDorisRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportMiraDBDataToDoris", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportMiraDBDataToDoris indicates an expected call of ImportMiraDBDataToDoris.
func (mr *MockIDorisServiceMockRecorder) ImportMiraDBDataToDoris(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportMiraDBDataToDoris", reflect.TypeOf((*MockIDorisService)(nil).ImportMiraDBDataToDoris), arg0)
}

// InitGlobalResource mocks base method.
func (m *MockIDorisService) InitGlobalResource() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitGlobalResource")
	ret0, _ := ret[0].(error)
	return ret0
}

// InitGlobalResource indicates an expected call of InitGlobalResource.
func (mr *MockIDorisServiceMockRecorder) InitGlobalResource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitGlobalResource", reflect.TypeOf((*MockIDorisService)(nil).InitGlobalResource))
}

// InitMiraTaskTmpDatabase mocks base method.
func (m *MockIDorisService) InitMiraTaskTmpDatabase() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitMiraTaskTmpDatabase")
	ret0, _ := ret[0].(error)
	return ret0
}

// InitMiraTaskTmpDatabase indicates an expected call of InitMiraTaskTmpDatabase.
func (mr *MockIDorisServiceMockRecorder) InitMiraTaskTmpDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitMiraTaskTmpDatabase", reflect.TypeOf((*MockIDorisService)(nil).InitMiraTaskTmpDatabase))
}

// ProcessDataSourceAndExport mocks base method.
func (m *MockIDorisService) ProcessDataSourceAndExport(arg0 *datasource.ReadDataSourceStreamingRequest, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessDataSourceAndExport", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessDataSourceAndExport indicates an expected call of ProcessDataSourceAndExport.
func (mr *MockIDorisServiceMockRecorder) ProcessDataSourceAndExport(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessDataSourceAndExport", reflect.TypeOf((*MockIDorisService)(nil).ProcessDataSourceAndExport), arg0, arg1)
}

// SwitchDatabase mocks base method.
func (m *MockIDorisService) SwitchDatabase(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchDatabase", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchDatabase indicates an expected call of SwitchDatabase.
func (mr *MockIDorisServiceMockRecorder) SwitchDatabase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchDatabase", reflect.TypeOf((*MockIDorisService)(nil).SwitchDatabase), arg0)
}
