// Code generated by MockGen. DO NOT EDIT.
// Source: client_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	oss "data-service/oss"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	lifecycle "github.com/minio/minio-go/v7/pkg/lifecycle"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// BucketExists mocks base method.
func (m *MockClientInterface) BucketExists(bucketName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BucketExists", bucketName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BucketExists indicates an expected call of BucketExists.
func (mr *MockClientInterfaceMockRecorder) BucketExists(bucketName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BucketExists", reflect.TypeOf((*MockClientInterface)(nil).BucketExists), bucketName)
}

// DeleteObject mocks base method.
func (m *MockClientInterface) DeleteObject(ctx context.Context, bucketName, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, bucketName, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockClientInterfaceMockRecorder) DeleteObject(ctx, bucketName, objectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockClientInterface)(nil).DeleteObject), ctx, bucketName, objectName)
}

// DeleteObjectsByJobInstanceId mocks base method.
func (m *MockClientInterface) DeleteObjectsByJobInstanceId(ctx context.Context, bucketName, jobInstanceId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectsByJobInstanceId", ctx, bucketName, jobInstanceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectsByJobInstanceId indicates an expected call of DeleteObjectsByJobInstanceId.
func (mr *MockClientInterfaceMockRecorder) DeleteObjectsByJobInstanceId(ctx, bucketName, jobInstanceId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectsByJobInstanceId", reflect.TypeOf((*MockClientInterface)(nil).DeleteObjectsByJobInstanceId), ctx, bucketName, jobInstanceId)
}

// DirectoryExists mocks base method.
func (m *MockClientInterface) DirectoryExists(bucketName, dir string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectoryExists", bucketName, dir)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DirectoryExists indicates an expected call of DirectoryExists.
func (mr *MockClientInterfaceMockRecorder) DirectoryExists(bucketName, dir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectoryExists", reflect.TypeOf((*MockClientInterface)(nil).DirectoryExists), bucketName, dir)
}

// GetObject mocks base method.
func (m *MockClientInterface) GetObject(ctx context.Context, bucketName, objectName string, opts *oss.GetOptions) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, bucketName, objectName, opts)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockClientInterfaceMockRecorder) GetObject(ctx, bucketName, objectName, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockClientInterface)(nil).GetObject), ctx, bucketName, objectName, opts)
}

// ListObjects mocks base method.
func (m *MockClientInterface) ListObjects(ctx context.Context, bucketName, prefix string, recursive bool) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, bucketName, prefix, recursive)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockClientInterfaceMockRecorder) ListObjects(ctx, bucketName, prefix, recursive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockClientInterface)(nil).ListObjects), ctx, bucketName, prefix, recursive)
}

// MakeBucket mocks base method.
func (m *MockClientInterface) MakeBucket(bucketName, location string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeBucket", bucketName, location)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeBucket indicates an expected call of MakeBucket.
func (mr *MockClientInterfaceMockRecorder) MakeBucket(bucketName, location interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeBucket", reflect.TypeOf((*MockClientInterface)(nil).MakeBucket), bucketName, location)
}

// PresignedGetObject mocks base method.
func (m *MockClientInterface) PresignedGetObject(bucketName, mergedFileName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedGetObject", bucketName, mergedFileName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedGetObject indicates an expected call of PresignedGetObject.
func (mr *MockClientInterfaceMockRecorder) PresignedGetObject(bucketName, mergedFileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedGetObject", reflect.TypeOf((*MockClientInterface)(nil).PresignedGetObject), bucketName, mergedFileName)
}

// PutObject mocks base method.
func (m *MockClientInterface) PutObject(ctx context.Context, bucketName, objectName string, reader io.Reader, objectSize int64, opts *oss.PutOptions) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, bucketName, objectName, reader, objectSize, opts)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockClientInterfaceMockRecorder) PutObject(ctx, bucketName, objectName, reader, objectSize, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockClientInterface)(nil).PutObject), ctx, bucketName, objectName, reader, objectSize, opts)
}

// SetBucketLifecycle mocks base method.
func (m *MockClientInterface) SetBucketLifecycle(bucketName string, lifecycleConfig *lifecycle.Configuration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBucketLifecycle", bucketName, lifecycleConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBucketLifecycle indicates an expected call of SetBucketLifecycle.
func (mr *MockClientInterfaceMockRecorder) SetBucketLifecycle(bucketName, lifecycleConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBucketLifecycle", reflect.TypeOf((*MockClientInterface)(nil).SetBucketLifecycle), bucketName, lifecycleConfig)
}
