// Code generated by MockGen. DO NOT EDIT.
// Source: C:\software\go\src\data-service\mocks\mock_streaming_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	datasource "data-service/generated/datasource"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockConcreteClientStreamingServer is a mock of ConcreteClientStreamingServer interface.
type MockConcreteClientStreamingServer struct {
	ctrl     *gomock.Controller
	recorder *MockConcreteClientStreamingServerMockRecorder
}

// MockConcreteClientStreamingServerMockRecorder is the mock recorder for MockConcreteClientStreamingServer.
type MockConcreteClientStreamingServerMockRecorder struct {
	mock *MockConcreteClientStreamingServer
}

// NewMockConcreteClientStreamingServer creates a new mock instance.
func NewMockConcreteClientStreamingServer(ctrl *gomock.Controller) *MockConcreteClientStreamingServer {
	mock := &MockConcreteClientStreamingServer{ctrl: ctrl}
	mock.recorder = &MockConcreteClientStreamingServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConcreteClientStreamingServer) EXPECT() *MockConcreteClientStreamingServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockConcreteClientStreamingServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockConcreteClientStreamingServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockConcreteClientStreamingServer)(nil).Context))
}

// Header mocks base method.
func (m *MockConcreteClientStreamingServer) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockConcreteClientStreamingServerMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockConcreteClientStreamingServer)(nil).Header))
}

// Recv mocks base method.
func (m *MockConcreteClientStreamingServer) Recv() (*datasource.OSSWriteRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*datasource.OSSWriteRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockConcreteClientStreamingServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockConcreteClientStreamingServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockConcreteClientStreamingServer) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockConcreteClientStreamingServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockConcreteClientStreamingServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockConcreteClientStreamingServer) Send(arg0 *datasource.ArrowResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockConcreteClientStreamingServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockConcreteClientStreamingServer)(nil).Send), arg0)
}

// SendAndClose mocks base method.
func (m *MockConcreteClientStreamingServer) SendAndClose(arg0 *datasource.Response) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndClose", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockConcreteClientStreamingServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndClose", reflect.TypeOf((*MockConcreteClientStreamingServer)(nil).SendAndClose), arg0)
}

// SendHeader mocks base method.
func (m *MockConcreteClientStreamingServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockConcreteClientStreamingServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockConcreteClientStreamingServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockConcreteClientStreamingServer) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockConcreteClientStreamingServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockConcreteClientStreamingServer)(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockConcreteClientStreamingServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockConcreteClientStreamingServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockConcreteClientStreamingServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockConcreteClientStreamingServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockConcreteClientStreamingServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockConcreteClientStreamingServer)(nil).SetTrailer), arg0)
}
