// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.0--rc2
// source: proto/mira_ida_access_service.proto

package mirapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MiraIdaAccess_GetPrivateDBConnInfo_FullMethodName        = "/mira.MiraIdaAccess/GetPrivateDBConnInfo"
	MiraIdaAccess_GetPrivateAssetInfoByEnName_FullMethodName = "/mira.MiraIdaAccess/GetPrivateAssetInfoByEnName"
)

// MiraIdaAccessClient is the client API for MiraIdaAccess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IDA Access Service 定义
type MiraIdaAccessClient interface {
	// 获取包含隐私信息的数据源连接信息接口
	GetPrivateDBConnInfo(ctx context.Context, in *GetPrivateDBConnInfoRequest, opts ...grpc.CallOption) (*GetPrivateDBConnInfoResponse, error)
	// 通过资产英文名称获取资产详情
	GetPrivateAssetInfoByEnName(ctx context.Context, in *GetPrivateAssetInfoByEnNameRequest, opts ...grpc.CallOption) (*GetPrivateAssetInfoByEnNameResponse, error)
}

type miraIdaAccessClient struct {
	cc grpc.ClientConnInterface
}

func NewMiraIdaAccessClient(cc grpc.ClientConnInterface) MiraIdaAccessClient {
	return &miraIdaAccessClient{cc}
}

func (c *miraIdaAccessClient) GetPrivateDBConnInfo(ctx context.Context, in *GetPrivateDBConnInfoRequest, opts ...grpc.CallOption) (*GetPrivateDBConnInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivateDBConnInfoResponse)
	err := c.cc.Invoke(ctx, MiraIdaAccess_GetPrivateDBConnInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miraIdaAccessClient) GetPrivateAssetInfoByEnName(ctx context.Context, in *GetPrivateAssetInfoByEnNameRequest, opts ...grpc.CallOption) (*GetPrivateAssetInfoByEnNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivateAssetInfoByEnNameResponse)
	err := c.cc.Invoke(ctx, MiraIdaAccess_GetPrivateAssetInfoByEnName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiraIdaAccessServer is the server API for MiraIdaAccess service.
// All implementations must embed UnimplementedMiraIdaAccessServer
// for forward compatibility.
//
// IDA Access Service 定义
type MiraIdaAccessServer interface {
	// 获取包含隐私信息的数据源连接信息接口
	GetPrivateDBConnInfo(context.Context, *GetPrivateDBConnInfoRequest) (*GetPrivateDBConnInfoResponse, error)
	// 通过资产英文名称获取资产详情
	GetPrivateAssetInfoByEnName(context.Context, *GetPrivateAssetInfoByEnNameRequest) (*GetPrivateAssetInfoByEnNameResponse, error)
	mustEmbedUnimplementedMiraIdaAccessServer()
}

// UnimplementedMiraIdaAccessServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiraIdaAccessServer struct{}

func (UnimplementedMiraIdaAccessServer) GetPrivateDBConnInfo(context.Context, *GetPrivateDBConnInfoRequest) (*GetPrivateDBConnInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivateDBConnInfo not implemented")
}
func (UnimplementedMiraIdaAccessServer) GetPrivateAssetInfoByEnName(context.Context, *GetPrivateAssetInfoByEnNameRequest) (*GetPrivateAssetInfoByEnNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivateAssetInfoByEnName not implemented")
}
func (UnimplementedMiraIdaAccessServer) mustEmbedUnimplementedMiraIdaAccessServer() {}
func (UnimplementedMiraIdaAccessServer) testEmbeddedByValue()                       {}

// UnsafeMiraIdaAccessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiraIdaAccessServer will
// result in compilation errors.
type UnsafeMiraIdaAccessServer interface {
	mustEmbedUnimplementedMiraIdaAccessServer()
}

func RegisterMiraIdaAccessServer(s grpc.ServiceRegistrar, srv MiraIdaAccessServer) {
	// If the following call pancis, it indicates UnimplementedMiraIdaAccessServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiraIdaAccess_ServiceDesc, srv)
}

func _MiraIdaAccess_GetPrivateDBConnInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateDBConnInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiraIdaAccessServer).GetPrivateDBConnInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiraIdaAccess_GetPrivateDBConnInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiraIdaAccessServer).GetPrivateDBConnInfo(ctx, req.(*GetPrivateDBConnInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiraIdaAccess_GetPrivateAssetInfoByEnName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateAssetInfoByEnNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiraIdaAccessServer).GetPrivateAssetInfoByEnName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiraIdaAccess_GetPrivateAssetInfoByEnName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiraIdaAccessServer).GetPrivateAssetInfoByEnName(ctx, req.(*GetPrivateAssetInfoByEnNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MiraIdaAccess_ServiceDesc is the grpc.ServiceDesc for MiraIdaAccess service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiraIdaAccess_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mira.MiraIdaAccess",
	HandlerType: (*MiraIdaAccessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrivateDBConnInfo",
			Handler:    _MiraIdaAccess_GetPrivateDBConnInfo_Handler,
		},
		{
			MethodName: "GetPrivateAssetInfoByEnName",
			Handler:    _MiraIdaAccess_GetPrivateAssetInfoByEnName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mira_ida_access_service.proto",
}
